apiVersion: v1
kind: Service
metadata:
  name: mongoauth
  labels:
    app: mongoauth
    role: master
    tier: backend
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongoauth
    role: master
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoauth
spec:
  selector:
    matchLabels:
      app: mongoauth
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mongoauth
        role: master
        tier: backend
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongoauth-pvc