apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongoauth-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/mongo"